name: WorldEdit
version: 1.0.0
api: [2.0.0]
author: Thunder33345
description:
main: Thunder33345\WorldEdit\Loader

#commands:
#  cmd:
#    permission: ""
#    usage: ""
#    permission: ""
#    alias: [cmd]

permissions:
  cmd:
    default: true
    description: ""